name: 'Publish Packages'

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  MSBUILDSINGLELOADCONTEXT: 1

jobs:
  generateVersionInfo:
    name: 'GenerateVersionInfo'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Restore dotnet tools'
        run: dotnet tool restore
      - name: 'Generate version info from git history'
        run: dotnet gitversion /output json | jq -r 'to_entries|map("GitVersion_\(.key)=\(.value|tostring)")|.[]' >> gitversion.env && cat gitversion.env
      - name: 'Upload version info file'
        uses: actions/upload-artifact@v3
        with:
          name: gitversion
          path: gitversion.env

  build:
    name: 'Build'
    needs: generateVersionInfo
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Download version info file'
        uses: actions/download-artifact@v1
        with:
          name: gitversion
          path: ./
      - name: 'Inject version info into environment'
        run: cat ./gitversion.env >> $GITHUB_ENV
      - name: 'Build solution'
        run: echo "Current version is \"$GitVersion_SemVer\"" && dotnet build -c Release
      - name: 'Create NuGet packages'
        run: dotnet pack -c Release --no-build -o packages
      - name: 'Upload NuGet packages'
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: packages

  publish:
    name: 'Publish'
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'push' }}
    steps:
      - name: 'Download NuGet packages'
        uses: actions/download-artifact@v3
        with:
          name: packages
          path: packages
      - name: 'Publish the package to Nuget.org'
        if: startsWith(github.ref, 'refs/tags/v')
        run: dotnet nuget push "*.nupkg" --source https://api.nuget.org/v3/index.json --api-key "${{ secrets.NUGET_API_KEY }}" --skip-duplicate --no-symbols true
        working-directory: packages
      - name: 'Publish the package to GitHub Packages'
        run: dotnet nuget push "*.nupkg" --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key "${{ secrets.GITHUB_TOKEN }}" --skip-duplicate --no-symbols true
        working-directory: packages